// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} ownerObject - The object with the reference set you want to clear
 * @param {string} referenceSetName - Include the module name
 * @returns {Promise.<void>}
 */
export async function RefSet_Clear(ownerObject, referenceSetName) {
	// BEGIN USER CODE
	// ad
	if (
		ownerObject.isObjectReferenceSet(referenceSetName) 
	) {
		ownerObject.set(referenceSetName, []);
	} else {
		throw new Error(
			`The reference set ${referenceSetName} was not found.`
		);
	}
	// END USER CODE
}
